# Generated by Django 3.2.9 on 2021-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('class_name', models.IntegerField()),
                ('contact_number', models.CharField(max_length=50)),
                ('fee_due', models.IntegerField()),
            ],
        ),
    ]
