# Generated by Django 3.2.9 on 2021-12-08 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Created_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
