# Generated by Django 3.2.9 on 2021-12-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_blog_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Blog_name',
            new_name='created_by',
        ),
    ]
