# Generated by Django 3.2.9 on 2021-12-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.CharField(max_length=50)),
            ],
        ),
    ]
