# Generated by Django 3.2.9 on 2021-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
