# Generated by Django 3.2.9 on 2021-12-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(height_field=300, upload_to='static/blog_images', width_field=300),
        ),
    ]
