# Generated by Django 3.2.9 on 2021-12-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_blog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/blog_images'),
        ),
    ]
